FROM liveui/boost-base:1.2.0

WORKDIR /app

#COPY .build ./.build
COPY Resources ./Resources
COPY Sources ./Sources
COPY Tests ./Tests
COPY Package.swift ./
COPY Package.resolved ./
COPY scripts/wait-for-it.sh ./
