version: '2.4'

services:
    api:
        image: liveui/boost-base:2.0
        ports:
            - "8080:8080"
        restart: on-failure
        environment:
            apicore.server.name: BoostCore
            apicore.database.host: postgres
            apicore.database.user: boost
            apicore.database.password: boost
            apicore.database.database: boost
            apicore.database.port: 5432
            apicore.jwt_secret: secret
            apicore.storage.s3.enabled: 0
            apicore.storage.local.root: /home/BoostCore
        volumes:
          - .:/app
        working_dir: /app
        depends_on:
            - postgres

    postgres:
        image: postgres:11-alpine
        restart: always
        environment:
            POSTGRES_USER: boost
            POSTGRES_PASSWORD: boost
            POSTGRES_DB: boost-test
