version: '2.4'

services:
    api:
        image: liveui/boost-base:2.0
        volumes:
          - .:/app
        working_dir: /app

    postgres:
        environment:
            POSTGRES_DB: boost-test
