version: '3.1'

dns:
  - 1.1.1.1
  - 8.8.8.8
  - 9.9.9.9

services:
    web:
        build: 
            context: .
            dockerfile: docker/base/Dockerfile
        ports:
            - "8080:8080"
        environment:
            apicore.server.name: BoostCore
            apicore.database.host: db
            apicore.database.user: dbuser
            apicore.database.password: aaaaaa
            apicore.database.database: dbuser
        depends_on:
            - "db"
        command: ["./wait-for-it.sh", "db:5432", "--", "swift", "test"]
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: dbuser
            POSTGRES_PASSWORD: aaaaaa
            POSTGRES_DB: dbuser
