version: 2
jobs:

  test:
    working_directory: /src
    docker:
      - image: einstore/einstore-base:2.0
      - image: postgres:11-alpine
        name: postgres
        environment:
          POSTGRES_USER: einstore
          POSTGRES_PASSWORD: einstore
          POSTGRES_DB: einstore
    environment:
      APICORE_SERVER_NAME: EinstoreCore
      APICORE_DATABASE_HOST: postgres
      APICORE_DATABASE_USER: einstore
      APICORE_DATABASE_PASSWORD: einstore
      APICORE_DATABASE_DATABASE: einstore
      APICORE_DATABASE_PORT: 5432
      APICORE_JWT_SECRET: secret
      APICORE_STORAGE_S3_ENABLED: 0
      APICORE_STORAGE_LOCAL_ROOT: /home/BoostCore
    steps:
      - checkout
      - run:
          command: swift test


  build:
    working_directory: /src
    docker:
      - image: docker:stable
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - restore_cache:
          keys:
            - docker-build-v1
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/.tar | true
      - run:
          command: |
            docker build --cache-from=einstore/einstore-core -t einstore/einstore-core:${CIRCLE_SHA1} .
      - run:
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          command: docker push einstore/einstore-core:${CIRCLE_SHA1}
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar einstore/einstore-core
      - save_cache:
          key: docker-build-v1
          paths:
            - /caches/app.tar


  tag:
    working_directory: /src
    docker:
      - image: docker:stable
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          command: docker pull einstore/einstore-core:${CIRCLE_SHA1}
      - run:
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: docker tag and push
          command: /src/.circleci/tag-and-push.sh ${CIRCLE_SHA1}


  build-debug:
    working_directory: /src
    docker:
      - image: docker:stable
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - restore_cache:
          keys:
            - docker-build-debug-v1
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/.tar | true
      - run:
          command: |
            docker build --build-arg CONFIGURATION="debug" --cache-from=einstore/einstore-core -t einstore/einstore-core:${CIRCLE_SHA1}.debug .
      - run:
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          command: docker push einstore/einstore-core:${CIRCLE_SHA1}.debug
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar einstore/einstore-core
      - save_cache:
          key: docker-build-debug-v1
          paths:
            - /caches/app.tar


  tag-debug:
    working_directory: /src
    docker:
      - image: docker:stable
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          command: docker pull einstore/einstore-core:${CIRCLE_SHA1}.debug
      - run:
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: docker tag and push
          command: /src/.circleci/tag-and-push.sh ${CIRCLE_SHA1}.debug .debug



workflows:
  version: 2
  test-build-publish:
    jobs:
      - test
      - build:
          filters:
            tags:
              only: /.*/

      - build-debug

      - tag:
          requires:
            - test
            - build
          filters:
            tags:
              only: /.*/

      - tag-debug:
          requires:
            - test
            - build-debug
