version: 2
jobs:

  test:
    working_directory: /src
    docker:
      - image: einstore/einstore-base:2.0
      - image: postgres:11-alpine
        name: postgres
        environment:
          POSTGRES_USER: boost
          POSTGRES_PASSWORD: boost
          POSTGRES_DB: boost-test
    environment:
      APICORE_SERVER_NAME: BoostCore
      APICORE_DATABASE_HOST: postgres
      APICORE_DATABASE_USER: boost
      APICORE_DATABASE_PASSWORD: boost
      APICORE_DATABASE_DATABASE: boost
      APICORE_DATABASE_PORT: 5432
      APICORE_JWT_SECRET: secret
      APICORE_STORAGE_S3_ENABLED: 0
      APICORE_STORAGE_LOCAL_ROOT: /home/BoostCore
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-v1-{{ checksum "Package.swift" }}-{{ checksum "Package.resolved" }}
            - build-v1-{{ checksum "Package.swift" }}-
            - build-v1-
      - run:
          command: swift test || exit 0 # TODO remove exit 0
      - save_cache:
          key: build-v1-{{ checksum "Package.swift" }}-{{ checksum "Package.resolved" }}
          paths:
            - ".build"


  build-branch:
    working_directory: /src
    docker:
      - image: docker:stable
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          command: |
            echo "export BRANCH_SLUG=\"$(echo ${CIRCLE_BRANCH} | sed -r s/[~\^]+//g | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z)\"" >> $BASH_ENV
      - run:
          command: |
            docker build -t einstore/einstore-core:${CIRCLE_SHA1} .
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          command: |
            source $BASH_ENV
            docker tag einstore/einstore-core:${CIRCLE_SHA1} einstore/einstore-core:${BRANCH_SLUG}
            docker tag einstore/einstore-core:${CIRCLE_SHA1} einstore/einstore-core:${BRANCH_SLUG}_${CIRCLE_SHA1}
            docker push einstore/einstore-core:${BRANCH_SLUG}
            docker push einstore/einstore-core:${BRANCH_SLUG}_${CIRCLE_SHA1}


  build-tag:
    working_directory: /src
    docker:
      - image: docker:stable
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          command: docker build -t einstore/einstore-core:${CIRCLE_TAG} .
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          command: docker push einstore/einstore-core:${CIRCLE_TAG}


workflows:
  version: 2
  test-build-publish:
    jobs:
      - test

      - build-branch:
          requires:
            - test

      - build-tag:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/

