version: 2
jobs:

  test:
    working_directory: /src
    docker:
      - image: liveui/boost-base:2.0
      - image: postgres:11-alpine
        name: postgres
        environment:
          POSTGRES_USER: boost
          POSTGRES_PASSWORD: boost
          POSTGRES_DB: boost-test
    environment:
      apicore.server.name: BoostCore
      apicore.database.host: postgres
      apicore.database.user: boost
      apicore.database.password: boost
      apicore.database.database: boost # App adds `-test` for test targets
      apicore.database.port: 5432
      apicore.jwt_secret: secret
      apicore.storage.s3.enabled: 0
      apicore.storage.local.root: /home/BoostCore
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-v1-{{ checksum "Package.swift" }}-{{ checksum "Package.resolved" }}
            - build-v1-{{ checksum "Package.swift" }}-
            - build-v1-
      - run:
          command: swift test || exit 0 # TODO remove exit 0
      - save_cache:
          key: build-v1-{{ checksum "Package.swift" }}-{{ checksum "Package.resolved" }}
          paths:
            - ".build"


  build-branch:
    working_directory: /src
    docker:
      - image: docker:stable
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          command: export BRANCH_SLUG=$(echo ${CIRCLE_BRANCH} | sed -r s/[~\^]+//g | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z)
      - run:
          command: docker build -t liveui/boost-core:${CIRCLE_BRANCH} . --pull
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          command: docker push liveui/boost-core:${CIRCLE_BRANCH}


  build-tag:
    working_directory: /src
    docker:
      - image: docker:stable
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          command: docker build -t liveui/boost-core:${CIRCLE_TAG} . --pull
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          command: docker push liveui/boost-core:${CIRCLE_TAG}


  test-build:
    working_directory: /src
    docker:
      - image: docker:stable
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          command: docker build -t liveui/boost-core:test . --pull


workflows:
  version: 2
  test-build-publish:
    jobs:
      - test
      - test-build:
          requires:
            - test
          filters:
            branches:
              ignore: master

      - build-branch:
          requires:
            - test
          filters:
            branches:
              only: master

      - build-tag:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/

